version: '3.12'
services:
  api:
    build:
      context: .  # Указываем путь к папке с Dockerfile для "api"
      dockerfile: Dockerfile
    container_name: basic_app
    ports:
      - "3001:3000"  # Проброс порта
    volumes:
      - .:/app   # Подключение локальной папки dz5 как /app в контейнере
    restart: unless-stopped # Автоматический рестарт при сбоях
    working_dir: /app       # Указываем рабочую директорию
    command: python app.py  # Выполняем команду запуска

  console-app:
    build:
      context: .  # Путь к текущей директории для сборки "console-app"
      dockerfile: Dockerfile
    image: console-app:latest
    container_name: console-app
    command: python app.py
    working_dir: /app
    restart: unless-stopped # Автоматический рестарт
